__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader_effnet.yml',
  './include/optimizer_regnet.yml',
  './include/rtdetr_efficientnet.yml',
]

output_dir: ./output/rtdetr_efficientnet_6x_coco