__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader_regnet.yml',
  './include/optimizer_regnet.yml',
  './include/rtdetr_mobilenet.yml',
]

output_dir: ./output/rtdetr_mobilenet_6x_coco